baseURL: "https://wg.chenhe.me/"
description: "这也许是最好的开源手表图库。This is probably the best open source gallery on your watch."
defaultContentLanguage: en
defaultContentLanguageInSubdir: true

module:
  imports:
    - path: github.com/alex-shpak/hugo-book

markup:
  goldmark:
    renderer:
      ## Set to true if you have HTML content inside Markdown
      unsafe: true
  tableOfContents:
    startLevel: 1

outputs:
  home: ["HTML"]

title: Wear Gallery

languages:
  en:
    languageCode: en
    title: Wear Gallery
    weight: 1
    languageName: Englilsh
  zh:
    languageCode: zh
    title: 腕间图库
    weight: 2
    languageName: 简体中文

menu:
  # before: []
  after:
    - name: "Github"
      url: "https://github.com/ichenhe/wear-gallery"
      weight: 10
    - name: "Chenhe's Blog"
      url: "https://chenhe.me/"
      weight: 20

params:
  BookRepo: https://github.com/ichenhe/wear-gallery
  BookEditPath: edit/website
  BookSection: docs
