name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+**

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew test && ./gradlew copyReports

      - name: Upload reports
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: Test reports
          path: "build/uni-outs/report"
          if-no-files-found: warn

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew lint && ./gradlew copyReports

      - name: Upload reports
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: Lint reports
          path: "build/uni-outs/report"
          if-no-files-found: warn

  release:
    runs-on: ubuntu-latest
    needs: [ 'test', 'lint' ]
    env:
      WG_SIGNING_STORE_PWD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      WG_SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      WG_SIGNING_KEY_PWD: ${{ secrets.SIGNING_KEY_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: base64-to-file
        uses: narcodico/base64-to-path@v1
        with:
          filePath: keystore/release.jks
          encodedString: ${{ secrets.SIGNING_KEYSTORE }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembleRelease && ./gradlew copyApk && ./gradlew copyMapping

      - name: Upload Apks
        uses: actions/upload-artifact@v3
        with:
          name: apks
          path: "build/uni-outs/apk"
      - name: Upload Mappings
        uses: actions/upload-artifact@v3
        with:
          name: mappings
          path: "build/uni-outs/mapping"
      - name: Create release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: false
          artifactErrorsFailBuild: true
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "build/uni-outs/apk/mobile-release.apk,build/uni-outs/apk/wear-release.apk"
          prerelease: ${{ endsWith(github.ref_name, '-pre') || endsWith(github.ref_name, '-preview') }}
